### PR TITLE
Fix resource leaks with ChemComp

### LINKED ISSUE #395: Exception when too many files requested to AtomCache
When the same **AtomCache** is used to request for many structures (not at the same time) an Exception is thrown and the following message is given: **Too many open files**. 

It could indicate a resource or memory leak in **AtomCache**, by maintaining some files open (although the structure has already been downloaded). I get those Exceptions when downloading, in parallel 4 at the same time, more than 2K structures. I do not remember the Exception when I calculated the census the first time (6 months ago), although I am not sure if I was using exactly the same code. Any ideas?

This is the **stacktrace** of the Exception:

```java
java.io.FileNotFoundException: /scratch/cache/data/structures/divided/mmCIF/rl/1rlr.cif.gz (Too many open files)
	at java.io.FileInputStream.open(Native Method) ~[?:1.6.0_38]
	at java.io.FileInputStream.<init>(FileInputStream.java:140) ~[?:1.6.0_38]
	at org.biojava.nbio.core.util.FlatFileCache.addToCache(FlatFileCache.java:63) [classes/:?]
	at org.biojava.nbio.core.util.InputStreamProvider.getInputStreamFromFile(InputStreamProvider.java:247) [classes/:?]
	at org.biojava.nbio.core.util.InputStreamProvider.getInputStream(InputStreamProvider.java:163) [classes/:?]
	at org.biojava.nbio.structure.io.LocalPDBDirectory.getInputStream(LocalPDBDirectory.java:377) [classes/:?]
	at org.biojava.nbio.structure.io.LocalPDBDirectory.getStructureById(LocalPDBDirectory.java:343) [classes/:?]
	at org.biojava.nbio.structure.align.util.AtomCache.loadStructureFromCifByPdbId(AtomCache.java:1038) [classes/:?]
	at org.biojava.nbio.structure.align.util.AtomCache.getStructureForPdbId(AtomCache.java:1019) [classes/:?]
	at org.biojava.nbio.structure.scop.ScopDomain.loadStructure(ScopDomain.java:245) [classes/:?]
	at org.biojava.nbio.structure.align.client.StructureName.loadStructure(StructureName.java:349) [classes/:?]
	at org.biojava.nbio.structure.align.util.AtomCache.getStructure(AtomCache.java:394) [classes/:?]
	at demo.CeSymmMain$CeSymmWorker.run(CeSymmMain.java:1061) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.6.0_38]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [?:1.6.0_38]
	at java.util.concurrent.FutureTask.run(FutureTask.java:166) [?:1.6.0_38]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146) [?:1.6.0_38]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.6.0_38]
	at java.lang.Thread.run(Thread.java:701) [?:1.6.0_38]
``

### PR DESCRIPTION
**Pull request by sbliven**
Adds additional check that files and streams are being closed in the ChemComp providers.

Also changes the ChemCompGroupFactory's behavior so that it does cache "empty"/stub chemicals
(since they will still be empty for the next fetch), but clears the cache when the provider changes.
This ensures that stub chemicals from a Reduced provider don't poison future fetches with the full
Download provider.

This should fix #395. Waters were being treated as "empty" due to an unfortunate choice of
one-letter code, and therefor not cached, leading to thousands of open handles to HOH.cif.gz.

### CODE REVIEW

File: biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java [hunk 1]
```diff
@@ -166,62 +166,57 @@ private void split() throws IOException {
...
 		InputStreamProvider prov = new InputStreamProvider();
 
-		InputStream inStream = prov.getInputStream(f);
-
-		BufferedReader buf = new BufferedReader (new InputStreamReader (inStream));
+		try( BufferedReader buf = new BufferedReader (new InputStreamReader (prov.getInputStream(f)));
+				) {
+			String line = null;
+			line = buf.readLine ();
+			StringWriter writer = new StringWriter();
```
Comment (josemduarte) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java]: Nice! I didn't know you could do this kind of thing with Java 7. This is the reference for those that don't know (like me!): https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

File: biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ReducedChemCompProvider.java [hunk 2]
```diff
@@ -46,54 +46,46 @@
...
-		if ( inStream == null){
-			//System.out.println("Could not find chem comp: " + name + " ... using generic Chem Comp");
-			// could not find the chem comp definition for this in the jar file
-			logger.debug("Getting empty chem comp for {}",name);
-			ChemComp cc = getEmptyChemComp();
-			cc.setId(name);
-			return cc;
-		}
+		try {
+			try(InputStream inStream = this.getClass().getResourceAsStream("/chemcomp/"+name + ".cif.gz")) {
```
Comment (josemduarte) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ReducedChemCompProvider.java]: Shouldn't the try-with be inside the first try? The second try is redundant, isn't it?

File: biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java [hunk 3]
```diff
@@ -364,29 +359,20 @@ private static boolean downloadChemCompRecord(String recordName) {
...
 			HttpURLConnection uconn = HTTPConnectionTools.openHttpURLConnection(url);
 
-			InputStream conn = uconn.getInputStream();
-
-			FileOutputStream outPut = new FileOutputStream(localName);
-
-			GZIPOutputStream gzOutPut = new GZIPOutputStream(outPut);
+			try( PrintWriter pw = new PrintWriter(new GZIPOutputStream(new FileOutputStream(localName)));
+					BufferedReader fileBuffer = new BufferedReader(new InputStreamReader(uconn.getInputStream()));
+					) {
```
Comment (josemduarte) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java]: This try is redundant, isn't it? The try-with could go above with the first try.

File: biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java (hunk 1 above)
Comment (sbliven) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java]: Yep! I'm going to milk the 1 month of Java 7 development for all its worth. I'm also using [type inference](https://docs.oracle.com/javase/tutorial/java/generics/genTypeInference.html) in all my code from now on.

File: biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java (hunk 3 above)
Comment (sbliven) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/DownloadChemCompProvider.java]: In this case I think not, because `openHttpURLConnection` can throw the exceptions as well. I wanted the try-with to surround only the stream code.

File: biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ReducedChemCompProvider.java (hunk 2 above)
Comment (sbliven) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ReducedChemCompProvider.java]: In this case it is redundant. I wasn't sure if you could combine catch blocks with try-with, but apparently you can.

File: biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ChemCompGroupFactory.java [hunk 4]
```diff
@@ -79,6 +77,8 @@ public static ChemComp getChemComp(String recordName){
 	public static void setChemCompProvider(ChemCompProvider provider) {
 		logger.debug("Setting new chem comp provider to "+provider.getClass().getCanonicalName());
 		chemCompProvider = provider;
+		// clear cache
+		cache.clear();
```
Comment (sbliven) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ChemCompGroupFactory.java]: Are there any potential problems here? I know there was discussion that we should do this dating back to before github, so I was very surprised that it hadn't been done.

Comment (josemduarte) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/io/mmcif/ChemCompGroupFactory.java]: Yes this looks familiar... I don't really remember what was the problem exactly but I'm pretty sure we've had a lot of subtle issues around how the cache is initialised and cleared. See for instance #313 

Let's anyway merge it so that we can test it for a while before the release. I know that @abradle is doing a lot of parallel parsing of files and he would be able to find problems with this.

**Comment by andreasprlic** [comment]
nice catch!
