### PR TITLE
Fix #933 URLConnection to invalid HTTP URL is not detected as failure

### LINKED ISSUE #933: URLConnection to invalid HTTP URL is not detected as a failure
TestDownloadChemCompProvider.testIfWeCachedGarbageWeCanDetectIt() still fails to detect when the target URL is invalid or the file has no contents. Instead of deleting the local cache file, a 20 bytes file (effectively an empty one) is saved.
Related to #703

### PR DESCRIPTION
**Pull request by aalhossary**
When the httpConnection is invalid, the application does not detect it, and it saves an empty (precisely a 20 bytes) file.
This fix detects when the connection is invalid or the file has no contents.
Related to #703
Adding a flag to be successful only when at least one byte is successfully read from the server

### CODE REVIEW

File: biojava-structure/src/main/java/org/biojava/nbio/structure/chem/DownloadChemCompProvider.java [hunk 1]
```diff
@@ -320,8 +319,13 @@ private static boolean downloadChemCompRecord(String recordName) {
             try (PrintWriter pw = new PrintWriter(new GZIPOutputStream(new FileOutputStream(newFile)));
                  BufferedReader fileBuffer = new BufferedReader(new InputStreamReader(uconn.getInputStream()))) {
                 String line;
+                boolean success = false;
                 while ((line = fileBuffer.readLine()) != null) {
                     pw.println(line);
+                    success = true;
+                }
+                if(!success) {
+                	throw new IOException("Could not read from URL "+url.toString());
```
Comment (josemduarte) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/chem/DownloadChemCompProvider.java:328]: Could you be more specific in the error message: `"Found no content in URL" + ...`

**Review by josemduarte — CHANGES_REQUESTED** [review]
Thanks! One comment about the error message

File: biojava-structure/src/main/java/org/biojava/nbio/structure/chem/DownloadChemCompProvider.java (hunk 1 above)
Comment (aalhossary) [reply biojava-structure/src/main/java/org/biojava/nbio/structure/chem/DownloadChemCompProvider.java:328]: OK. I will mention the two possible reasons

**Review by josemduarte — APPROVED** [review]
Thanks!

**Comment by josemduarte** [comment]
@aalhossary , we are having some trouble with the CI tests. Could you try pushing an empty commit (`git commit --allow-empty -m "Trigger Build"
`) to see if that triggers the tests?
