### PR TITLE
Fixing issue with Calc.transform(Chain,Matrix4d)

### LINKED ISSUE #715: Calc.transform(Chain) does not transform alt groups
Looks like an issue in master branch and in 4.2.x branch.

### PR DESCRIPTION
**Pull request by josemduarte**
Should fix #715

### CODE REVIEW

File: biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java [hunk 1]
```diff
@@ -601,12 +601,14 @@ public static final void translate(Atom atom, Vector3d v) {
...
-		AtomIterator iter = new AtomIterator(group);
 
-		while (iter.hasNext()) {
-			Atom atom = iter.next();
+		for (Atom atom : group.getAtoms()) {
 			translate(atom, v);
-
+		}
+		for (Group altG : group.getAltLocs()) {
+			for (Atom atom : altG.getAtoms()) {
```
Comment (lafita) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java]: Why not using `translate(g, v)`? It would be a recursive call to this function, nicer solution.

File: biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java [hunk 2]
```diff
@@ -538,12 +538,13 @@ public static final void transform(Atom atom, Matrix4d m) {
...
-		AtomIterator iter = new AtomIterator(group);
-
-		while (iter.hasNext()) {
-			Atom atom = iter.next();
+		for (Atom atom : group.getAtoms()) {
 			transform(atom, m);
-
+		}
+		for (Group altG : group.getAltLocs()) {
+			for (Atom atom : altG.getAtoms()) {
```
Comment (lafita) [inline biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java]: Recursive call to `transform(g, m)` could also be possible here.

Comment (josemduarte) [reply biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java]: Good point, now changed
